create table book_store (
    id bigint primary key,
    name varchar(200) not null
);
create table book (
    id bigint generated by default as identity primary key,
    name varchar(200) not null unique,
    price numeric(12, 2) not null,
    version integer not null default 0,
    tenant_id varchar(100) not null,
    store_id bigint references book_store(id)
);
create index book_store_id_idx on book(store_id);
insert into book_store values (10, 'Library');
